spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:feedbackdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    clean-disabled: false
    locations: >
      classpath:db/migration,
      classpath:dev/db/migration

logging:
  level:
    root: INFO
    com.env.feedback: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.validator: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  user:
    password: admin
    email: admin@feedback.com